version: '3.4'

services:
  bots34:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./compose/bots_py34/Dockerfile
    ports:
      - 9000:9000

  db:
    image: postgres
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${USER_NAME}"
      POSTGRES_PASSWORD: "${USER_PASSWORD}"
    ports:
      - 5432:5432

  migrate:
    depends_on:
      - db
    build:
      context: ./database
