version: '2'

# Database by SQLITE
# Config settings copied from install

services:
  bots34:
    build:
      context: .
      dockerfile: ./compose/bots_py34/Dockerfile
    ports:
      - "0.0.0.0:8080:8080"
